services:
  - type: web
    name: rag-pipeline-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn scr.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.14
      - key: PDF_DIRECTORY
        value: data/pdf
      - key: PERSIST_DIRECTORY
        value: data/vector_store
